--LAB-1 SQL CONCEPTS REVISION
--DATABASE NAME: BRANCH_DIV_ROLLNO (EXAMPLE: CSE_3A_101 OR BSC_HONS_101)
--NOTE: CREATE ALL THE TABLES UNDER ABOVE DATABASE WITH DESIGN MODE ONLY.

CREATE DATABASE CSE_4B_490

--PART – A

--1. RETRIEVE A UNIQUE GENRE OF SONGS.
	SELECT DISTINCT GENRE 
	FROM SONGS

--2. FIND TOP 2 ALBUMS RELEASED BEFORE 2010.
	SELECT TOP 2 * 
	FROM ALBUMS
	WHERE RELEASE_YEAR<2010

--3. INSERT DATA INTO THE SONGS TABLE. (1245, ‘ZAROOR’, 2.55, ‘FEEL GOOD’, 1005)
	INSERT INTO SONGS VALUES(1245,'ZAROOR',2.55,'FEEL GOOD',1005)

--4. CHANGE THE GENRE OF THE SONG ‘ZAROOR’ TO ‘HAPPY’
	UPDATE SONGS 
	SET GENRE = 'HAPPY'
	WHERE SONG_TITLE = 'ZAROOR'

--5. DELETE AN ARTIST ‘ED SHEERAN’
	DELETE FROM	ARTIST
	WHERE ARTIST_NAME = 'ED SHREERAN'
	
	SELECT * FROM ARTISTS

--6. ADD A NEW COLUMN FOR RATING IN SONGS TABLE. [RATINGS DECIMAL(3,2)]
	ALTER TABLE SONGS
	ADD RATINGS DECIMAL(3,2)

	SELECT * FROM SONGS

--7.RETRIEVE SONGS WHOSE TITLE STARTS WITH 'S'.
	SELECT SONG_TITLE FROM SONGS
	WHERE SONG_TITLE LIKE 'S%'

--8. RETRIEVE ALL SONGS WHOSE TITLE CONTAINS 'EVERYBODY'.
	SELECT SONG_TITLE FROM SONGS
	WHERE SONG_TITLE LIKE '%EVERYBODY%'

--9. DISPLAY ARTIST NAME IN UPPERCASE.
	SELECT UPPER(ARTIST_NAME) FROM ARTISTS

--10. FIND THE SQUARE ROOT OF THE DURATION OF A SONG ‘GOOD LUCK’
	SELECT SQRT(DURATION) FROM SONGS
	WHERE SONG_TITLE = 'GOOD LUCK'

--11. FIND CURRENT DATE.
	SELECT GETDATE() AS CURRENTDATE

--12. FIND THE NUMBER OF ALBUMS FOR EACH ARTIST.
	SELECT ARTIST_ID,COUNT(ALBUM_TITLE) FROM ALBUMS
	GROUP BY ARTIST_ID
	 
--13. RETRIEVE THE ALBUM_ID WHICH HAS MORE THAN 5 SONGS IN IT.
	SELECT A.ALBUM_ID, COUNT(S.SONG_ID)
	FROM ALBUMS A JOIN SONGS S ON A.ALBUM_ID = S.ALBUM_ID
	GROUP BY A.ALBUM_ID
	HAVING COUNT(S.SONG_ID) > 5;

--14. RETRIEVE ALL SONGS FROM THE ALBUM 'ALBUM1'. (USING SUBQUERY)
	SELECT SONG_TITLE
	FROM SONGS
	WHERE ALBUM_ID = (SELECT ALBUM_ID
					  FROM ALBUMS
					  WHERE ALBUM_TITLE = 'ALBUM1');

--15. RETRIEVE ALL ALBUMS NAME FROM THE ARTIST ‘APARSHAKTI KHURANA’ (USING SUBQUERY)
	SELECT ALBUM_TITLE
	FROM ALBUMS
	WHERE ARTIST_ID = (SELECT ARTIST_ID
	FROM ARTISTS
	WHERE ARTIST_NAME = 'APARSHAKTI KHURANA');

--16. RETRIEVE ALL THE SONG TITLES WITH ITS ALBUM TITLE.
	SELECT S.SONG_TITLE, A.ALBUM_TITLE
	FROM SONGS S JOIN ALBUMS A ON S.ALBUM_ID = A.ALBUM_ID;

--17. FIND ALL THE SONGS WHICH ARE RELEASED IN 2020.
	SELECT *
	FROM SONGS S JOIN ALBUMS A ON S.ALBUM_ID = A.ALBUM_ID
	WHERE A.RELEASE_YEAR = 2020;

--18. CREATE A VIEW CALLED ‘FAV_SONGS’ FROM THE SONGS TABLE HAVING SONGS WITH SONG_ID 101-105.
	CREATE VIEW FAV_SONGS
	AS
		SELECT *
		FROM SONGS
		WHERE SONG_ID BETWEEN 101 AND 105;

--19. UPDATE A SONG NAME TO ‘JANNAT’ OF SONG HAVING SONG_ID 101 IN FAV_SONGS VIEW.
	UPDATE FAV_SONGS
	SET SONG_TITLE = 'JANNAT'
	WHERE SONG_ID = 101;

--20. FIND ALL ARTISTS WHO HAVE RELEASED AN ALBUM IN 2020.
	SELECT *
	FROM ARTISTS A JOIN ALBUMS B ON A.ARTIST_ID = B.ARTIST_ID
	WHERE B.RELEASE_YEAR = 2020;

--21. RETRIEVE ALL SONGS BY SHREYA GHOSHAL AND ORDER THEM BY DURATION.
	SELECT *
	FROM SONGS S
		JOIN ALBUMS A ON S.ALBUM_ID = A.ALBUM_ID
		JOIN ARTISTS B ON A.ARTIST_ID = B.ARTIST_ID
	WHERE B.ARTIST_NAME = 'SHREYA GHOSAL';


--PART – B


--22. RETRIEVE ALL SONG TITLES BY ARTISTS WHO HAVE MORE THAN ONE ALBUM.
	SELECT B.ARTIST_NAME, S.SONG_TITLE
	FROM SONGS S
		JOIN ALBUMS A ON S.ALBUM_ID = A.ALBUM_ID
		JOIN ARTISTS B ON A.ARTIST_ID = B.ARTIST_ID
	WHERE B.ARTIST_ID IN (
		SELECT B.ARTIST_ID
	FROM ALBUMS B
	GROUP BY B.ARTIST_ID
	HAVING COUNT(B.ALBUM_ID) > 1
	)

--23. RETRIEVE ALL ALBUMS ALONG WITH THE TOTAL NUMBER OF SONGS.
	SELECT A.ALBUM_TITLE, COUNT(S.SONG_ID)
	FROM ALBUMS A JOIN SONGS S ON A.ALBUM_ID = S.ALBUM_ID
	GROUP BY A.ALBUM_TITLE;

--24. RETRIEVE ALL SONGS AND RELEASE YEAR AND SORT THEM BY RELEASE YEAR.
	SELECT S.*, A.RELEASE_YEAR
	FROM SONGS S JOIN ALBUMS A ON S.ALBUM_ID = A.ALBUM_ID
	ORDER BY A.RELEASE_YEAR;

--25. RETRIEVE THE TOTAL NUMBER OF SONGS FOR EACH GENRE, SHOWING GENRES THAT HAVE MORE THAN 2 SONGS.
	SELECT GENRE, COUNT(SONG_ID)
	FROM SONGS
	GROUP BY GENRE
	HAVING COUNT(SONG_ID) > 2;

--26. LIST ALL ARTISTS WHO HAVE ALBUMS THAT CONTAIN MORE THAN 3 SONGS.
	SELECT DISTINCT A.ARTIST_NAME
	FROM ARTISTS A JOIN ALBUMS B ON A.ARTIST_ID = B.ARTIST_ID JOIN SONGS S ON B.ALBUM_ID = S.ALBUM_ID
	WHERE B.ALBUM_ID IN (
		SELECT ALBUM_ID
	FROM SONGS
	GROUP BY ALBUM_ID
	HAVING COUNT(SONG_ID)>3
)
--PART – C

--27. RETRIEVE ALBUMS THAT HAVE BEEN RELEASED IN THE SAME YEAR AS 'ALBUM4'
	SELECT ALBUM_TITLE
	FROM ALBUMS
	WHERE RELEASE_YEAR = (SELECT RELEASE_YEAR
	FROM ALBUMS
	WHERE ALBUM_TITLE = 'ALBUM4');

--28. FIND THE LONGEST SONG IN EACH GENRE
	SELECT GENRE, MAX(DURATION)
	FROM SONGS
	GROUP BY GENRE;

--29. RETRIEVE THE TITLES OF SONGS RELEASED IN ALBUMS THAT CONTAIN THE WORD 'ALBUM' IN THE TITLE.
	SELECT S.SONG_TITLE, A.ALBUM_TITLE
	FROM SONGS S JOIN ALBUMS A ON S.ALBUM_ID = A.ALBUM_ID
	WHERE A.ALBUM_TITLE LIKE '%ALBUM%';

--30. RETRIEVE THE TOTAL DURATION OF SONGS BY EACH ARTIST WHERE TOTAL DURATION EXCEEDS 15 MINUTES.
	SELECT A.ARTIST_NAME, SUM(S.DURATION)
	FROM ARTISTS A
		JOIN ALBUMS B ON A.ARTIST_ID = B.ARTIST_ID
		JOIN SONGS S ON B.ALBUM_ID = S.ALBUM_ID
	GROUP BY A.ARTIST_NAME;
